'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
const pagoda='វត្តព្រះពុទ្ធសោភ័ណ្ឌបរិបុណ្ណារាម'; const mapUrl='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(pagoda); const trip=new Date('2026-10-10T06:00:00+07:00');
type Guest={name:string;status:'ទៅ'|'មិនទៅ'};
export default function Home(){
 const [count,setCount]=useState(''),[guests,setGuests]=useState<Guest[]>([{name:'អ្នករៀបចំ',status:'ទៅ'}]),[name,setName]=useState(''),[status,setStatus]=useState<Guest['status']>('ទៅ'),[music,setMusic]=useState(false); const ctx=useRef<AudioContext|null>(null), loop=useRef<number|null>(null);
 useEffect(()=>{const s=localStorage.getItem('guests');if(s)setGuests(JSON.parse(s));const f=()=>{let d=trip.getTime()-Date.now();if(d<=0)return setCount('ដល់ថ្ងៃទៅវត្តហើយ! 🙏');setCount(`${Math.floor(d/86400000)} ថ្ងៃ ${Math.floor(d%86400000/3600000)} ម៉ោង ${Math.floor(d%3600000/60000)} នាទី ${Math.floor(d%60000/1000)} វិនាទី`)};f();const t=setInterval(f,1000);return()=>clearInterval(t)},[]);
 const rsvp=(e:FormEvent)=>{e.preventDefault();if(!name.trim())return;const n=[...guests.filter(x=>x.name!==name.trim()),{name:name.trim(),status}];setGuests(n);localStorage.setItem('guests',JSON.stringify(n));setName('')};
 const toggle=()=>{if(!ctx.current){const C=window.AudioContext||(window as any).webkitAudioContext;ctx.current=new C()} if(music){if(loop.current)clearInterval(loop.current);setMusic(false);return} const notes=[261.63,293.66,329.63,392,440,392,329.63,293.66];let i=0;const play=()=>{const o=ctx.current!.createOscillator(),g=ctx.current!.createGain();o.type='sine';o.frequency.value=notes[i++%notes.length];g.gain.setValueAtTime(.0001,ctx.current!.currentTime);g.gain.exponentialRampToValueAtTime(.07,ctx.current!.currentTime+.05);g.gain.exponentialRampToValueAtTime(.0001,ctx.current!.currentTime+1.3);o.connect(g).connect(ctx.current!.destination);o.start();o.stop(ctx.current!.currentTime+1.35)};play();loop.current=window.setInterval(play,900);setMusic(true)};
 const schedule=[['០៦:០០','ជួបជុំគ្នា','ជួបគ្នា ពិនិត្យសម្ភារៈ និងត្រៀមចេញដំណើរ','🌅'],['០៦:៣០','ចេញដំណើរ','ធ្វើដំណើរទៅវត្តជាមួយគ្នា','🛵'],['០៧:៣០','ទៅដល់វត្ត','រៀបចំចង្ហាន់ និងគ្រឿងបូជា','🙏'],['០៨:០០','ធ្វើបុណ្យ','ប្រគេនចង្ហាន់ ស្តាប់ព្រះធម៌ និងចូលរួមពិធី','🪷'],['១០:០០','ជួបជុំ & ថតរូប','ថតរូបជាក្រុម និងរក្សាអនុស្សាវរីយ៍','📸'],['១២:០០','អាហារថ្ងៃត្រង់','ញ៉ាំអាហារជាមួយគ្នា និងបញ្ចប់កម្មវិធី','🍚']];
 return <main><div className="petals">{Array.from({length:12},(_,i)=><span key={i}>🌸</span>)}</div><section className="hero"><div className="pattern"/><div className="lantern l1">🏮</div><div className="lantern l2">🏮</div><nav><b>🙏 ភ្ជុំបិណ្ឌ ២០២៦</b><div><button onClick={toggle}>{music?'🔔 ភ្លេង ON':'🎵 ភ្លេង'}</button><a href="#details">ព័ត៌មាន</a></div></nav><div className="heroContent"><p className="eyebrow">១០ • ១០ • ២០២៦</p><h1>ទៅវត្ត<br/><span>ជាមួយមិត្តភក្តិ</span></h1><p className="lead">មួយថ្ងៃសម្រាប់ការជួបជុំ ធ្វើបុណ្យ និងចែករំលែកស្នាមញញឹម។</p><div className="dateCard"><div>ថ្ងៃ<strong>សៅរ៍</strong></div><i/><div>កាលបរិច្ឆេទ<strong>១០ តុលា ២០២៦</strong></div><i/><div>ចាប់ផ្តើម<strong>៦:០០ ព្រឹក</strong></div></div><div className="buttons"><a className="primary" href="#details">មើលកម្មវិធី ↓</a><a className="outline" href={mapUrl} target="_blank">📍 Google Maps</a></div></div></section>
 <section className="count"><p>រាប់ថយក្រោយដល់ថ្ងៃទៅវត្ត</p><strong>{count}</strong></section><section className="location"><div><p className="eyebrow">DESTINATION</p><h2>{pagoda}</h2><p>គោលដៅរបស់ពួកយើងនៅថ្ងៃបុណ្យភ្ជុំបិណ្ឌ។</p></div><a className="primary" href={mapUrl} target="_blank">📍 ទៅកាន់ទីតាំង</a></section>
 <section id="details" className="content"><div className="heading"><p className="eyebrow">ITINERARY</p><h2>កម្មវិធីលម្អិត</h2><p>ចាប់ពីព្រឹករហូតដល់ថ្ងៃត្រង់ — រៀបចំឱ្យងាយស្រួលសម្រាប់គ្រប់គ្នា។</p></div><div className="timeline">{schedule.map(x=><article key={x[0]}><b>{x[0]}</b><em>{x[3]}</em><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div></section>
 <section className="gallery"><div className="heading"><p className="eyebrow">MEMORIES</p><h2>Photo Gallery 📸</h2><p>កន្លែងសម្រាប់ដាក់រូបថតពីដំណើររបស់ពួកយើង។</p></div><div className="photos">{['🙏','🪷','🏮','❤️','📸','🍚'].map((x,i)=><div key={i}><span>{x}</span><small>រូបថត {i+1}</small></div>)}</div><p className="hint">💡 អ្នកអាចប្តូរ card ទាំងនេះទៅជា រូបថតពិតរបស់ក្រុមបាន។</p></section>
 <section className="quote"><b>“</b><p>បុណ្យភ្ជុំបិណ្ឌ គឺជាពេលវេលានៃការចងចាំ ការដឹងគុណ និងការជួបជុំ។</p><span>— សួស្តីបុណ្យភ្ជុំបិណ្ឌ 🙏</span></section>
 <section className="rsvp"><div className="heading"><p className="eyebrow">FRIENDS RSVP</p><h2>អ្នកណាខ្លះទៅ? 👥</h2><p>បញ្ចូលឈ្មោះរបស់អ្នក ដើម្បីបញ្ជាក់ថាទៅជាមួយក្រុម។</p></div><form onSubmit={rsvp}><input value={name} onChange={e=>setName(e.target.value)} placeholder="ឈ្មោះរបស់អ្នក..."/><select value={status} onChange={e=>setStatus(e.target.value as Guest['status'])}><option>ទៅ</option><option>មិនទៅ</option></select><button>បញ្ជាក់ RSVP</button></form><div className="guests">{guests.map(g=><div className="guest" key={g.name}><span>{g.name[0]}</span><b>{g.name}</b><small className={g.status==='ទៅ'?'yes':'no'}>{g.status}</small></div>)}</div></section>
 <section className="friends"><p className="eyebrow">FRIENDS DAY</p><h2>មកជាមួយគ្នា ❤️</h2><p>កុំភ្លេចអាវស្អាតៗ កាមេរ៉ា និងស្នាមញញឹមរបស់អ្នក!</p><button onClick={()=>document.querySelector<HTMLInputElement>('.rsvp input')?.focus()}>ខ្ញុំទៅជាមួយ! 🙌</button></section><footer><b>🙏 បុណ្យភ្ជុំបិណ្ឌ ២០២៦</b><span>{pagoda}</span><span>Made with ❤️ for friends & family</span></footer></main>}
